// Package store defines the storage layer interface, with the specific implementation provided by internal/store.
package store

import (
	"time"

	"github.com/rulego/rulego/api/types"
	"github.com/rulego/rulego/server/model"
)

// RuleStore Rule Chain Storage interface
type RuleStore interface {
	// Save the rule chain definition
	Save(username, chainId string, def []byte) error
	// Get the original JSON data of the rule chain
	Get(username, chainId string) ([]byte, error)
	// GetAsRuleChain Retrieves the rule chain struct
	GetAsRuleChain(username, chainId string) (types.RuleChain, error)
	// List lists the rule chain (frontend UI-oriented): keyword search, root/disabled filtering, category filtering, pagination sorting.
	// It filters the SystemAgent chain; To start and load, please use AllChains.
	List(username, keywords string, root *bool, disabled *bool, category string, size, page int) ([]types.RuleChain, int, error)
	// AllChains returns the ID and original DSL (including SystemAgent) for all rule chains under the specified user at once.
	// Used to start loading and avoid N+1 queries generated by each Get query.
	// If a single chain fails, it will be skipped (without interrupting the whole), and the order is not defined.
	AllChains(username string) (map[string][]byte, error)
	// Delete: Remove the rule chain
	Delete(username, chainId string) error
}

// UserStore user storage interface
type UserStore interface {
	// CreateUser creates a user
	CreateUser(user model.User) error
	// ValidatePassword: Verify the password
	ValidatePassword(username, password string) bool
	// Delete: Remove the user
	Delete(username string) error
	// List lists all users
	List() []model.User
}

// SettingStore user settings for the storage interface
type SettingStore interface {
	// Save
	Save(key, value string) error
	// Get the set value
	Get(key string) string
	// Delete the settings
	Delete(key string) error
	// Setting to obtain the complete user settings
	Setting() model.UserSetting
}

// RunLogStore runs the log storage interface
type RunLogStore interface {
	// Save the runlog
	Save(username string, event model.Event) error
	// List displays runtime logs, supports filtering by chainId and time range, and pagination
	List(username, chainId string, startTime, endTime time.Time, size, page int) ([]model.Event, int, error)
	// Get a single runtime log
	Get(username, logId string) (model.Event, error)
	// Delete: Deletes the runtime log
	Delete(username, logId string) error
	// DeleteByChainId deletes all runtime logs of the specified rule chain
	DeleteByChainId(username, chainId string) error
}

// ComponentStore component storage interface
type ComponentStore interface {
	// Save saves component definitions
	Save(username, componentId string, def []byte) error
	// Get the component definition
	Get(username, componentId string) ([]byte, error)
	// List Lists components
	List(username, keywords string, size, page int) ([][]byte, int, error)
	// Delete: Remove components
	Delete(username, componentId string) error
}

// NodePoolStore node pool storage interface
type NodePoolStore interface {
	// Save saves node pool data
	Save(data []byte) error
	// Get the node pool data
	Get() ([]byte, error)
}

// LocaleStore international storage interface
type LocaleStore interface {
	// Save the language pack
	Save(lang string, data []byte) error
	// Get the language pack
	Get(lang string) ([]byte, error)
	// List all languages
	List() ([]string, error)
}

// StoreProvider interface, used to create and retrieve various Store instances.
// The default implementation is filestore.FileStoreProvider (file-based storage).
// Users can access the app through the app.WithStoreProvider injects custom implementations (such as database storage).
type StoreProvider interface {
	// GetRuleStore retrieves the rule chain storage (per-user, with cache) for a specified user.
	GetRuleStore(username string) (RuleStore, error)
	// GetSettingStore retrieves the settings storage for the specified user (per-user, with cache)
	GetSettingStore(username string) (SettingStore, error)
	// GetComponentStore retrieves the component storage (per-user, with cache) for the specified user.
	GetComponentStore(username string) (ComponentStore, error)
	// GetNodePoolStore Retrieves the node pool storage (per-user, with cache) for the specified user.
	GetNodePoolStore(username string) (NodePoolStore, error)
	// GetUserStore Retrieves user storage (global singleton)
	GetUserStore() (UserStore, error)
	// GetRunLogStore retrieves the runtime log store (global singleton)
	GetRunLogStore() (RunLogStore, error)
}
